name: aio_logs
description: Log Apps
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  aio_flutter:
    git: https://github.com/venosyd/aio_flutter.git
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  permission_handler: ^5.0.1+1
  responsive_builder: ^0.1.3
  universal_io: ^1.0.1
  universal_platform: ^0.1.3
  yaml: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/png/
  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/butler.otf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/opensans.ttf
    - family: Open Sans Light
      fonts:
        - asset: assets/fonts/opensans-light.ttf
