name: aio_logs
description: Log Apps
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  permission_handler: ^5.0.1+1
  responsive_builder: ^0.1.3
  universal_platform: ^0.1.3
  universal_io: ^1.0.1
  yaml: ^2.2.1
  aio_flutter:
    # path: ../aio_flutter
    git: git@github.com:venosyd/aio_flutter.git

flutter:
  uses-material-design: true
  assets:
    - assets/png/
  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/butler.otf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/opensans.ttf
    - family: Open Sans Light
      fonts:
        - asset: assets/fonts/opensans-light.ttf
